version: '3.7'

services:
  api:
    build:
      context: ./
    image: flight-data-service
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_FAA_DATA_DIR_PATH=/app/data
